import type { DocumentKind } from '../../core/types';

export type KindProfile = {
  plural: string;
  singular: string;
  meaning: string;
  formIntro: string;
  partyRole: 'customer' | 'vendor' | null;
  partyLabel: string;
  partyHint: string;
  issueDateLabel: string;
  dueDateLabel: string | null;
  memoLabel: string;
  memoPlaceholder: string;
  referenceLabel: string | null;
  referencePlaceholder: string;
  placeOfSupplyLabel: string | null;
  billToLabel: string | null;
  billToPlaceholder: string;
  shipToLabel: string | null;
  shipToPlaceholder: string;
  notesLabel: string | null;
  notesPlaceholder: string;
  termsLabel: string | null;
  defaultTerms: string;
  linePlaceholder: string;
  qtyLabel: string;
  rateLabel: string;
  accountLabel: string;
  showQty: boolean;
  showTax: boolean;
  showInterstate: boolean;
  showAccount: boolean;
  showProject: boolean;
  convertTo: DocumentKind | null;
  convertLabel: string | null;
  canPost: boolean;
  canPay: boolean;
  canPrint: boolean;
  listParty: string;
  listRef: string;
  listDue: string | null;
  fileLabel: string;
  fileHint: string;
  createLabel: string;
  accountSide: 'income' | 'spend';
};

const PROFILES: Record<DocumentKind, KindProfile> = {
  invoice: {
    plural: 'Invoices',
    singular: 'Invoice',
    meaning: 'A tax invoice to a customer. Posting creates the receivable journal. Payment later clears AR.',
    formIntro: 'Bill the customer. GST is computed from tax codes — do not type the tax amount.',
    partyRole: 'customer',
    partyLabel: 'Customer',
    partyHint: 'Who owes this invoice',
    issueDateLabel: 'Invoice date',
    dueDateLabel: 'Payment due',
    memoLabel: 'Internal memo',
    memoPlaceholder: 'Not printed — staff only',
    referenceLabel: 'Customer PO',
    referencePlaceholder: 'PO they sent you',
    placeOfSupplyLabel: 'Place of supply',
    billToLabel: 'Bill to',
    billToPlaceholder: 'Legal name, billing address, GSTIN',
    shipToLabel: 'Ship to',
    shipToPlaceholder: 'Delivery address if different',
    notesLabel: 'Notes on invoice',
    notesPlaceholder: 'Printed for the customer',
    termsLabel: 'Payment terms',
    defaultTerms: 'Payment due as per terms. Goods once sold are subject to the recorded tax treatment.',
    linePlaceholder: 'Item or service billed',
    qtyLabel: 'Qty',
    rateLabel: 'Rate',
    accountLabel: 'Income account',
    showQty: true,
    showTax: true,
    showInterstate: true,
    showAccount: true,
    showProject: true,
    convertTo: null,
    convertLabel: null,
    canPost: true,
    canPay: true,
    canPrint: true,
    listParty: 'Customer',
    listRef: 'Customer PO',
    listDue: 'Balance',
    fileLabel: 'Attach PO or contract',
    fileHint: 'Customer PO, contract, or delivery note. 8 MB max.',
    createLabel: 'New invoice',
    accountSide: 'income',
  },
  estimate: {
    plural: 'Estimates',
    singular: 'Estimate',
    meaning: 'A ballpark for the customer. It does not post a journal. Convert it to an invoice when the job is confirmed.',
    formIntro: 'Rough value only. This is not a tax invoice and does not hit the ledger.',
    partyRole: 'customer',
    partyLabel: 'Customer',
    partyHint: 'Who this estimate is for',
    issueDateLabel: 'Estimate date',
    dueDateLabel: 'Valid until',
    memoLabel: 'Job / site notes',
    memoPlaceholder: 'Site, scope, assumptions',
    referenceLabel: 'Enquiry / tender ref',
    referencePlaceholder: 'Their enquiry number',
    placeOfSupplyLabel: 'Place of supply',
    billToLabel: 'Prepared for',
    billToPlaceholder: 'Customer name and address',
    shipToLabel: 'Job / site location',
    shipToPlaceholder: 'Where the work would happen',
    notesLabel: 'Scope notes',
    notesPlaceholder: 'What is included or excluded',
    termsLabel: 'Estimate conditions',
    defaultTerms: 'This is an estimate, not a tax invoice. Prices may change before a firm quote or invoice.',
    linePlaceholder: 'Estimated work or material',
    qtyLabel: 'Est. qty',
    rateLabel: 'Est. rate',
    accountLabel: 'Likely income account',
    showQty: true,
    showTax: true,
    showInterstate: true,
    showAccount: true,
    showProject: true,
    convertTo: 'invoice',
    convertLabel: 'Convert to invoice',
    canPost: false,
    canPay: false,
    canPrint: true,
    listParty: 'Customer',
    listRef: 'Enquiry ref',
    listDue: 'Valid until',
    fileLabel: 'Attach enquiry or drawings',
    fileHint: 'Tender, drawings, or site photos. 8 MB max.',
    createLabel: 'New estimate',
    accountSide: 'income',
  },
  quote: {
    plural: 'Quotes',
    singular: 'Quote',
    meaning: 'A firm commercial offer. It does not post a journal. Convert it to an invoice when the customer accepts.',
    formIntro: 'Quoted prices and tax. Still not a tax invoice until you convert and post.',
    partyRole: 'customer',
    partyLabel: 'Customer',
    partyHint: 'Who this quote is for',
    issueDateLabel: 'Quote date',
    dueDateLabel: 'Valid until',
    memoLabel: 'Internal memo',
    memoPlaceholder: 'Staff notes — not printed',
    referenceLabel: 'RFQ / customer ref',
    referencePlaceholder: 'Their RFQ number',
    placeOfSupplyLabel: 'Place of supply',
    billToLabel: 'Quote addressed to',
    billToPlaceholder: 'Legal name, address, GSTIN',
    shipToLabel: 'Deliver / perform at',
    shipToPlaceholder: 'Delivery or service location',
    notesLabel: 'Notes on quote',
    notesPlaceholder: 'Printed for the customer',
    termsLabel: 'Quote terms',
    defaultTerms: 'This quotation is not a tax invoice. Acceptance is required before supply.',
    linePlaceholder: 'Quoted item or service',
    qtyLabel: 'Qty',
    rateLabel: 'Quoted rate',
    accountLabel: 'Income account',
    showQty: true,
    showTax: true,
    showInterstate: true,
    showAccount: true,
    showProject: true,
    convertTo: 'invoice',
    convertLabel: 'Convert to invoice',
    canPost: false,
    canPay: false,
    canPrint: true,
    listParty: 'Customer',
    listRef: 'RFQ',
    listDue: 'Valid until',
    fileLabel: 'Attach RFQ or spec',
    fileHint: 'Customer RFQ or specification. 8 MB max.',
    createLabel: 'New quote',
    accountSide: 'income',
  },
  sales_order: {
    plural: 'Sales Orders',
    singular: 'Sales order',
    meaning: 'A confirmed order to fulfil. It does not post a journal. Convert to an invoice when you bill the shipment.',
    formIntro: 'What the customer ordered and when they want it. Billing happens on the invoice.',
    partyRole: 'customer',
    partyLabel: 'Customer',
    partyHint: 'Who placed the order',
    issueDateLabel: 'Order date',
    dueDateLabel: 'Requested delivery',
    memoLabel: 'Fulfilment notes',
    memoPlaceholder: 'Warehouse or packing notes',
    referenceLabel: 'Customer PO',
    referencePlaceholder: 'PO they sent you',
    placeOfSupplyLabel: 'Place of supply',
    billToLabel: 'Bill to',
    billToPlaceholder: 'Invoicing address',
    shipToLabel: 'Deliver to',
    shipToPlaceholder: 'Ship-to address',
    notesLabel: 'Order notes',
    notesPlaceholder: 'Printed on the order acknowledgement',
    termsLabel: 'Order terms',
    defaultTerms: 'This sales order confirms supply. A tax invoice will follow on delivery or as agreed.',
    linePlaceholder: 'Ordered item',
    qtyLabel: 'Order qty',
    rateLabel: 'Agreed rate',
    accountLabel: 'Income account',
    showQty: true,
    showTax: true,
    showInterstate: true,
    showAccount: true,
    showProject: true,
    convertTo: 'invoice',
    convertLabel: 'Convert to invoice',
    canPost: false,
    canPay: false,
    canPrint: true,
    listParty: 'Customer',
    listRef: 'Customer PO',
    listDue: 'Deliver by',
    fileLabel: 'Attach customer PO',
    fileHint: 'Signed PO or order email. 8 MB max.',
    createLabel: 'New sales order',
    accountSide: 'income',
  },
  credit_note: {
    plural: 'Credit Notes',
    singular: 'Credit note',
    meaning: 'Reduces what a customer owes (returns, overbilling). Posting writes the reversing receivable journal.',
    formIntro: 'Link the original invoice and the reason. This is a correction, not a new sale.',
    partyRole: 'customer',
    partyLabel: 'Customer',
    partyHint: 'Customer being credited',
    issueDateLabel: 'Credit date',
    dueDateLabel: null,
    memoLabel: 'Reason for credit',
    memoPlaceholder: 'Return, price correction, or cancellation',
    referenceLabel: 'Original invoice no.',
    referencePlaceholder: 'INV-… being credited',
    placeOfSupplyLabel: 'Place of supply',
    billToLabel: 'Credit to',
    billToPlaceholder: 'Customer billing address',
    shipToLabel: null,
    shipToPlaceholder: '',
    notesLabel: 'Explanation on credit note',
    notesPlaceholder: 'Printed for the customer',
    termsLabel: null,
    defaultTerms: '',
    linePlaceholder: 'Item or amount being credited',
    qtyLabel: 'Qty credited',
    rateLabel: 'Credit rate',
    accountLabel: 'Income account to reverse',
    showQty: true,
    showTax: true,
    showInterstate: true,
    showAccount: true,
    showProject: false,
    convertTo: null,
    convertLabel: null,
    canPost: true,
    canPay: false,
    canPrint: true,
    listParty: 'Customer',
    listRef: 'Original invoice',
    listDue: 'Unapplied',
    fileLabel: 'Attach return or original invoice',
    fileHint: 'Return note or the invoice being credited. 8 MB max.',
    createLabel: 'New credit note',
    accountSide: 'income',
  },
  debit_note: {
    plural: 'Debit Notes',
    singular: 'Debit note',
    meaning: 'Increases what a customer owes (extra charges, underbilling). Posting writes an additional receivable journal.',
    formIntro: 'Charge an extra amount against an existing invoice. This is not a full new invoice.',
    partyRole: 'customer',
    partyLabel: 'Customer',
    partyHint: 'Customer being debited',
    issueDateLabel: 'Debit date',
    dueDateLabel: 'Payment due',
    memoLabel: 'Reason for debit',
    memoPlaceholder: 'Freight, price increase, or underbilling',
    referenceLabel: 'Original invoice no.',
    referencePlaceholder: 'INV-… being adjusted',
    placeOfSupplyLabel: 'Place of supply',
    billToLabel: 'Debit to',
    billToPlaceholder: 'Customer billing address',
    shipToLabel: null,
    shipToPlaceholder: '',
    notesLabel: 'Explanation on debit note',
    notesPlaceholder: 'Printed for the customer',
    termsLabel: 'Payment terms',
    defaultTerms: 'This debit note is payable with the related invoice.',
    linePlaceholder: 'Additional charge',
    qtyLabel: 'Qty',
    rateLabel: 'Extra rate',
    accountLabel: 'Income account',
    showQty: true,
    showTax: true,
    showInterstate: true,
    showAccount: true,
    showProject: false,
    convertTo: null,
    convertLabel: null,
    canPost: true,
    canPay: true,
    canPrint: true,
    listParty: 'Customer',
    listRef: 'Original invoice',
    listDue: 'Balance',
    fileLabel: 'Attach supporting charge',
    fileHint: 'Freight bill or price revision. 8 MB max.',
    createLabel: 'New debit note',
    accountSide: 'income',
  },
  purchase_request: {
    plural: 'Purchase Requests',
    singular: 'Purchase request',
    meaning: 'An internal ask to buy. It does not post a journal. Convert to a purchase order when approved to order.',
    formIntro: 'What you need and by when. Vendor can be suggested; ordering happens on the PO.',
    partyRole: 'vendor',
    partyLabel: 'Suggested vendor',
    partyHint: 'Optional preferred supplier',
    issueDateLabel: 'Request date',
    dueDateLabel: 'Needed by',
    memoLabel: 'Business reason',
    memoPlaceholder: 'Why this purchase is needed',
    referenceLabel: 'Cost centre / job',
    referencePlaceholder: 'Internal code',
    placeOfSupplyLabel: null,
    billToLabel: null,
    billToPlaceholder: '',
    shipToLabel: 'Deliver to',
    shipToPlaceholder: 'Office, site, or store',
    notesLabel: 'Requester notes',
    notesPlaceholder: 'Specs, brand, or constraints',
    termsLabel: null,
    defaultTerms: '',
    linePlaceholder: 'Item requested',
    qtyLabel: 'Qty needed',
    rateLabel: 'Est. unit cost',
    accountLabel: 'Likely expense account',
    showQty: true,
    showTax: false,
    showInterstate: false,
    showAccount: true,
    showProject: true,
    convertTo: 'purchase_order',
    convertLabel: 'Convert to purchase order',
    canPost: false,
    canPay: false,
    canPrint: true,
    listParty: 'Vendor',
    listRef: 'Cost centre',
    listDue: 'Needed by',
    fileLabel: 'Attach spec or quote',
    fileHint: 'Specification or vendor quote. 8 MB max.',
    createLabel: 'New purchase request',
    accountSide: 'spend',
  },
  purchase_order: {
    plural: 'Purchase Orders',
    singular: 'Purchase order',
    meaning: 'A commitment to a vendor. It does not post a journal. Convert to a bill when the vendor invoice arrives.',
    formIntro: 'What you are ordering and when you expect it. The bill is what hits AP.',
    partyRole: 'vendor',
    partyLabel: 'Vendor',
    partyHint: 'Who will supply',
    issueDateLabel: 'Order date',
    dueDateLabel: 'Expected delivery',
    memoLabel: 'Buyer notes',
    memoPlaceholder: 'Internal purchasing notes',
    referenceLabel: 'Our PR / contract',
    referencePlaceholder: 'PR number or contract',
    placeOfSupplyLabel: 'Place of supply',
    billToLabel: 'Bill to us at',
    billToPlaceholder: 'Your billing address for the vendor',
    shipToLabel: 'Deliver to',
    shipToPlaceholder: 'Warehouse or site',
    notesLabel: 'Notes to vendor',
    notesPlaceholder: 'Printed on the PO',
    termsLabel: 'PO terms',
    defaultTerms: 'Supply as per this purchase order. Invoice against the PO number.',
    linePlaceholder: 'Ordered item',
    qtyLabel: 'Order qty',
    rateLabel: 'Unit cost',
    accountLabel: 'Expense / asset account',
    showQty: true,
    showTax: true,
    showInterstate: true,
    showAccount: true,
    showProject: true,
    convertTo: 'bill',
    convertLabel: 'Convert to bill',
    canPost: false,
    canPay: false,
    canPrint: true,
    listParty: 'Vendor',
    listRef: 'PR / contract',
    listDue: 'Deliver by',
    fileLabel: 'Attach quote or PR',
    fileHint: 'Approved request or vendor quote. 8 MB max.',
    createLabel: 'New purchase order',
    accountSide: 'spend',
  },
  purchase_receipt: {
    plural: 'Purchase Receipts',
    singular: 'Purchase receipt',
    meaning: 'Records goods received against a PO. It does not post a journal. Convert to a bill to book the vendor invoice.',
    formIntro: 'What arrived and against which PO. Quantity received can differ from the order.',
    partyRole: 'vendor',
    partyLabel: 'Vendor',
    partyHint: 'Who delivered',
    issueDateLabel: 'Received on',
    dueDateLabel: null,
    memoLabel: 'GRN / gate notes',
    memoPlaceholder: 'Condition, shortage, or vehicle',
    referenceLabel: 'Against PO no.',
    referencePlaceholder: 'PO-… being received',
    placeOfSupplyLabel: null,
    billToLabel: null,
    billToPlaceholder: '',
    shipToLabel: 'Received at',
    shipToPlaceholder: 'Warehouse or site',
    notesLabel: 'Receiving notes',
    notesPlaceholder: 'Shortage, damage, or extra qty',
    termsLabel: null,
    defaultTerms: '',
    linePlaceholder: 'Item received',
    qtyLabel: 'Qty received',
    rateLabel: 'PO unit cost',
    accountLabel: 'Inventory / expense account',
    showQty: true,
    showTax: false,
    showInterstate: false,
    showAccount: true,
    showProject: false,
    convertTo: 'bill',
    convertLabel: 'Convert to bill',
    canPost: false,
    canPay: false,
    canPrint: true,
    listParty: 'Vendor',
    listRef: 'Against PO',
    listDue: null,
    fileLabel: 'Attach delivery challan',
    fileHint: 'Challan, GRN, or photos. 8 MB max.',
    createLabel: 'New goods receipt',
    accountSide: 'spend',
  },
  bill: {
    plural: 'Bills',
    singular: 'Bill',
    meaning: 'A vendor invoice to pay. Posting creates the payable journal. Payment later clears AP.',
    formIntro: 'Book the vendor’s invoice. GST is computed from tax codes — do not type the tax amount.',
    partyRole: 'vendor',
    partyLabel: 'Vendor',
    partyHint: 'Who you owe',
    issueDateLabel: 'Bill date',
    dueDateLabel: 'Payment due',
    memoLabel: 'Internal memo',
    memoPlaceholder: 'Staff only',
    referenceLabel: 'Vendor invoice no.',
    referencePlaceholder: 'Number on their invoice',
    placeOfSupplyLabel: 'Place of supply',
    billToLabel: 'Billed from',
    billToPlaceholder: 'Vendor name, address, GSTIN',
    shipToLabel: 'Ship / service to',
    shipToPlaceholder: 'Where goods or service were received',
    notesLabel: 'Notes to vendor',
    notesPlaceholder: 'Printed if you send a copy',
    termsLabel: 'Payment terms',
    defaultTerms: 'Pay as per the vendor invoice and agreed terms.',
    linePlaceholder: 'What was billed',
    qtyLabel: 'Qty',
    rateLabel: 'Unit cost',
    accountLabel: 'Expense / asset account',
    showQty: true,
    showTax: true,
    showInterstate: true,
    showAccount: true,
    showProject: true,
    convertTo: null,
    convertLabel: null,
    canPost: true,
    canPay: true,
    canPrint: true,
    listParty: 'Vendor',
    listRef: 'Vendor invoice',
    listDue: 'Balance',
    fileLabel: 'Attach vendor invoice',
    fileHint: 'Vendor PDF or scan. 8 MB max.',
    createLabel: 'New bill',
    accountSide: 'spend',
  },
  vendor_credit: {
    plural: 'Vendor Credits',
    singular: 'Vendor credit',
    meaning: 'Reduces what you owe a vendor (returns or overbilling). Posting writes the reversing payable journal.',
    formIntro: 'Link the original bill and the reason. This is a vendor credit, not a payment.',
    partyRole: 'vendor',
    partyLabel: 'Vendor',
    partyHint: 'Vendor issuing the credit',
    issueDateLabel: 'Credit date',
    dueDateLabel: null,
    memoLabel: 'Reason for credit',
    memoPlaceholder: 'Return, rate correction, or discount',
    referenceLabel: 'Original bill / vendor credit no.',
    referencePlaceholder: 'Their credit note or our bill no.',
    placeOfSupplyLabel: 'Place of supply',
    billToLabel: 'Credit from',
    billToPlaceholder: 'Vendor address',
    shipToLabel: null,
    shipToPlaceholder: '',
    notesLabel: 'Notes',
    notesPlaceholder: 'Printed if needed',
    termsLabel: null,
    defaultTerms: '',
    linePlaceholder: 'Item or amount credited',
    qtyLabel: 'Qty credited',
    rateLabel: 'Credit rate',
    accountLabel: 'Expense account to reverse',
    showQty: true,
    showTax: true,
    showInterstate: true,
    showAccount: true,
    showProject: false,
    convertTo: null,
    convertLabel: null,
    canPost: true,
    canPay: false,
    canPrint: true,
    listParty: 'Vendor',
    listRef: 'Original bill',
    listDue: 'Unapplied',
    fileLabel: 'Attach vendor credit note',
    fileHint: 'Their credit note or return challan. 8 MB max.',
    createLabel: 'New vendor credit',
    accountSide: 'spend',
  },
  expense: {
    plural: 'Books Expenses',
    singular: 'Books expense',
    meaning: 'A cash/bank spend recorded in Books (not Expense Tracker). Posting writes the expense journal from the pay-from account.',
    formIntro: 'What was paid, from which cash/bank account, and to which expense account. No customer or vendor required.',
    partyRole: null,
    partyLabel: '',
    partyHint: '',
    issueDateLabel: 'Paid on',
    dueDateLabel: null,
    memoLabel: 'Paid to / description',
    memoPlaceholder: 'Shop, person, or purpose',
    referenceLabel: 'Receipt no.',
    referencePlaceholder: 'Receipt or UPI ref',
    placeOfSupplyLabel: null,
    billToLabel: null,
    billToPlaceholder: '',
    shipToLabel: null,
    shipToPlaceholder: '',
    notesLabel: null,
    notesPlaceholder: '',
    termsLabel: null,
    defaultTerms: '',
    linePlaceholder: 'What the money was for',
    qtyLabel: 'Qty',
    rateLabel: 'Amount',
    accountLabel: 'Expense account',
    showQty: false,
    showTax: true,
    showInterstate: false,
    showAccount: true,
    showProject: true,
    convertTo: null,
    convertLabel: null,
    canPost: true,
    canPay: false,
    canPrint: false,
    listParty: 'Payee',
    listRef: 'Receipt',
    listDue: null,
    fileLabel: 'Attach receipt',
    fileHint: 'Photo or PDF of the receipt. 8 MB max.',
    createLabel: 'New Books expense',
    accountSide: 'spend',
  },
};

export function documentProfile(kind: DocumentKind): KindProfile {
  return PROFILES[kind];
}
